### ISSUE TITLE
Cannot build Go encoder

### ISSUE THREAD

**Issue by Brixomatic** [tonysavon/TSCrunch#6]
`joshua@WOPR:~$ sudo apt install golang-go` # version 2:1.13~1ubuntu2
...
```console
joshua@WOPR:~$ git clone https://github.com/tonysavon/TSCrunch
Cloning into 'TSCrunch'...
...
joshua@WOPR:~$ cd TSCrunch/
joshua@WOPR:~/TSCrunch$ ls
LICENSE  README.md  TSCrunch.java  benchmark.png  bin  boot_code.h  decrunch.asm  decrunch_extreme.asm  decrunch_small.asm  readme.txt  tscrunch.c  tscrunch.go
joshua@WOPR:~/TSCrunch$ go build -o tscrunch tscrunch.go
# command-line-arguments
./tscrunch.go:185:15: undefined: os.ReadFile
./tscrunch.go:194:2: undefined: os.WriteFile
./tscrunch.go:200:25: cannot convert data[i:] (type []byte) to type *[3]byte
./tscrunch.go:320:25: cannot convert prefix (type []byte) to type *[3]byte
```

also the older build method that I used for an earlier version did not work:
```console
joshua@WOPR:~/TSCrunch$ mkdir -p bin/this
joshua@WOPR:~/TSCrunch$ go mod init tscrunch
go: creating new go.mod: module tscrunch
joshua@WOPR:~/TSCrunch$ go mod tidy
joshua@WOPR:~/TSCrunch$ go build -o bin/this/tscrunch
can't load package: package tscrunch: C source files not allowed when not using cgo or SWIG: tscrunch.c
```
tried again with 
`joshua@WOPR:~$ sudo apt install gccgo-go ` # version 2:1.13~1ubuntu2
...
```console
joshua@WOPR:~$ git clone https://github.com/tonysavon/TSCrunch
Cloning into 'TSCrunch'...
..
joshua@WOPR:~$ cd TSCrunch/
joshua@WOPR:~/TSCrunch$ go build -o tscrunch tscrunch.go
# command-line-arguments
./tscrunch.go:185:18: error: reference to undefined identifier ‘os.ReadFile’
  185 |  data, err := os.ReadFile(f)
      |                  ^
./tscrunch.go:194:5: error: reference to undefined identifier ‘os.WriteFile’
  194 |  os.WriteFile(f, data, 0666)
      |     ^
./tscrunch.go:113:44: error: shift count not unsigned integer
  113 |     specializedLiteralLengths |= uint32(1) << transition.size
      |                                            ^
./tscrunch.go:119:43: error: shift count not unsigned integer
  119 |    if specializedLiteralLengths&(uint32(1)<<size) != 0 {
      |                                           ^
./tscrunch.go:200:25: error: invalid type conversion
  200 |   key := *(*[MINLZ]byte)(data[i:])
      |                         ^
./tscrunch.go:320:25: error: invalid type conversion
  320 |   key := *(*[MINLZ]byte)(prefix)
      |                         ^
```

**Comment by tonysavon** [comment]
Fixed in #7. The Go encoder now builds with Go 1.13, including the reported gccgo shift-count compatibility issues. The documented build command is `go build -o tscrunch tscrunch.go`; `go build .` also picks up `tscrunch.c` and is not the intended Go-only build. I verified the fix with Go 1.13.15 and the current Go toolchain, with byte-identical compressed output.
